language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: sSPG6s6/oUvjZT5qGbvUBrlSYGvnrzPNDfMGhKSDZMuLWQ4GuH6MosNafDMdMhFZ5a2r862VEiLyMBunZO4Nzwi/qPz+3t2k02p+N11MGfUPQA2Cd3w30jfEA7smK6xqaD751F6h93IBNkSry8rhV05fVoB8TNmB9Jozl+eAlQ4sBHyqhFWdRWtGqEGGgWAqXJ+I8mz8nQjTbcEfkspqnyi6ch0AaR4ymkfvShAMYSuI55NCiIhQn+Clo1JjMZeoXyiVZHq7eW/PvEGhdVV6oPNCccIr2ZYjmAQ8q7GwVwoG3kU+LMrMX+vHcAREh6D5zzdnMvdnbYqGzha/2tjKOgbBAxxGuKJtN9/YXfSAVYnLI34ixNxbHwsjlw/psXUhGdAtJeIRItOcTGZebw6GaJ3aPSUKF0jsm0Kay7s18j2H3H6aDCobyP8564WeMhRNg9zZF1bFJsvemsOVJhZClZUUMrrkNNOWOi/NEpwNKsoKIOabeMI9IybkHA454e/3y6NWLPwTuHfq52Yx3h+IWCdimqvSS5TytybmJk4GeqXb80cBpx/0JstJQnMix3VBYvaJhuRC8odd1rBGInOX+g5Sc6750tckSlhq2qSLQaY/MHmGvt0sCzmNqJB8f8ADyEEtVO99rXD4Bjz6oLwSeKvv64EnqUkCWPh+AiARkTQ=

