language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: GaEAJkD2DflmVHEe62l+x5FwpvL3KG+eUEmmD6K4K6t74AuI4VYz8XAP7Fea5QlEoahdqGVPIQsCuM+Ir5pw02l5Dwb0NZD6b+GB+3Ax9CqFrOoLUCruxLM0+9BYOlIe4bpzjskNjV/lB5r164zcNRx/wfkvUn+Tw0zygk19onteNGEY/ap3cmiPWRFg1/Wpz8x8IbRbdy/j2xA0UvZ/N3A8IyGbrB+drb0VKpR4c0X3seKjAEWZCY62MnIaSqMoT3yeDpkD0YK1AazLYKqowe3Nhn/2NBq10fos76/0wjK6AXhbdkJ6UP3R6C8+dsg2gVAdQrp890Lw2IwNIUrrcs3Kt1dlebi9AN2WEAtVJQFNV2zd/PdnCTlhfyYsiQiviuVdeMoXBMXhGnuwUKWSmsOfP9TbkUXZfBAEbf/z3OnevZIgAsu5CSYOYNyJ+py7Qrn/VvfCIDbrG1bttLPucs3Xtp7bdmOcTq4FjimnZi6OTq8VW+Q0abMvw61uVt3riNEzGAQvzs3U7marZr3JRyWiCaKW/vl078ZW84okeeSCd1D0DDTkaOE6WJs03wRKW5UIRBs4MFoBnIZ6QTva/J0m/q5LQlDol5G6eOE7oKKPYddi046ltsdNY2YC4ZnrYJZ9x9/biDZ6vcGESYwHnd4jkQRLfFrwyG+xIz3mTLQ=
